trigger:
- none
#- main

pool:
  name: Default
  demands:
    - docker

stages:




- stage: Test
  displayName: 'Aut. tests stage'
  jobs:
  - job: TestJob
    displayName: 'Running automated tests'
    steps:
    - task: PowerShell@2
      displayName: 'Running aut. tests in the container'
      inputs:
        targetType: filePath
        filePath: 'C:\agent\_work\3\s\Scripts\AutoTests.ps1'



- stage: ReadyArtifacts
  displayName: 'Artifacts Stage'
  jobs:
    - job: PublishArtifacts
      displayName: 'Publishing artifacts ready to deploy'
      steps:
      - task: PublishPipelineArtifact@1
        displayName: 'Publish Artifact - Core'
        inputs:
          targetPath: 'C:\ProgramData\BcContainerHelper\Extensions\BCLatestDevOps\my\appProjectFolder\MyCore\output'
          artifact: 'My Core App'
          publishLocation: pipeline

      - task: PublishPipelineArtifact@1
        displayName: 'Publish Artifact - Test'
        inputs:
          targetPath: 'C:\ProgramData\BcContainerHelper\Extensions\BCLatestDevOps\my\appProjectFolder\TestApp\output'
          artifact: 'Test App'
          publishLocation: pipeline



# Add a section for removing the container in the end of the process        
# Add conditions