trigger:
- main

pool:
  name: Default
  demands:
    - docker

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job'
    steps:
    - checkout: self
    #- script: echo $(Build.Repository.LocalPath)
    #- task: PowerShell@1
      #inputs:
        #scriptType: inlineScript
        #inlineScript: |
          #Check-BcContainerHelperPermissions -Fix
          #$credential = [PSCredential]::new("admin", (ConvertTo-SecureString -String "Admin@123" -AsPlainText -Force)) 
          #Compile-AppInBcContainer -appProjectFolder C:\agent\_work\3\s -containerName BCLatest -AzureDevOps -FailOn error -credential $credential
    - task: PowerShell@2
      inputs:
        targetType: inline
        script: |
          $credential = [PSCredential]::new("admin", (ConvertTo-SecureString -String "Admin@123" -AsPlainText -Force)) 
          Compile-AppInBcContainer -appProjectFolder C:\agent\_work\3\s -containerName BCLatest -AzureDevOps -FailOn error -credential $credential