trigger:
- main

pool:
  name: Default
  demands:
    - docker

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    displayName: 'Build Job - MyCore + Test Apps'
    steps:
    - checkout: self
    - task: CopyFiles@2
      displayName: 'Copying repo files to container'
      inputs:
        SourceFolder: 'C:\agent\_work\3\s'
        Contents: '**'
        TargetFolder: 'C:\ProgramData\BcContainerHelper\Extensions\BCLatest\my\appProjectFolder'
        CleanTargetFolder: true

    - task: PowerShell@1
      displayName: 'Compile Core App'
      inputs:
        scriptType: inlineScript
        inlineScript: |
          $credential = [PSCredential]::new("admin", (ConvertTo-SecureString -String "Admin@123" -AsPlainText -Force)) 
          Compile-AppInBcContainer -appProjectFolder C:\ProgramData\BcContainerHelper\Extensions\BCLatest\my\appProjectFolder\MyCore -containerName BCLatest -AzureDevOps -FailOn error -credential $credential

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'C:\ProgramData\BcContainerHelper\Extensions\BCLatest\my\appProjectFolder\MyCore\output'
        artifact: 'My Core App'
        publishLocation: pipeline 

    - task: PowerShell@1
      displayName: 'Compile Test App'
      inputs:
        scriptType: inlineScript
        inlineScript: |
          $credential = [PSCredential]::new("admin", (ConvertTo-SecureString -String "Admin@123" -AsPlainText -Force)) 
          Compile-AppInBcContainer -appProjectFolder C:\ProgramData\BcContainerHelper\Extensions\BCLatest\my\appProjectFolder\TestApp -containerName BCLatest -AzureDevOps -FailOn error -credential $credential

    - task: PublishPipelineArtifact@1
      inputs:
        targetPath: 'C:\ProgramData\BcContainerHelper\Extensions\BCLatest\my\appProjectFolder\TestApp\output'
        artifact: 'Test App'
        publishLocation: pipeline